dist: trusty
sudo: false
language: python

cache: pip

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  
addons:
  apt:
    packages:
      - openjdk-8-jre
    
env:
  matrix:
    - ES_VERSION=5.4.1
    - ES_VERSION=5.3.3
    - ES_VERSION=2.4.5
    - ES_VERSION=1.7.6
    
install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch -d
  - pip install git+https://github.com/elastic/elasticsearch-py.git#egg=elasticsearch
  
script:
  - pip install -r requirements.txt
  - pip install coveralls nose2 nose2-cov
  - coverage run --source=nxtool -m nose2.__main__ -v

after_success:
  - coveralls
