dist: trusty
sudo: false
language: python

cache: pip

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  
addons:
  apt:
    packages:
      - openjdk-8-jre
    
env:
  matrix:
    - ES_VERSION=5.4.1
      DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
    - ES_VERSION=5.3.3
      DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
    - ES_VERSION=2.4.5
      DOWNLOAD_URL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz
    - ES_VERSION=1.7.6
      DOWNLOAD_URL=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
      
install:
  - mkdir /tmp/elasticsearch
  - wget -O - ${DOWNLOAD_URL} | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch -d
  - sleep 10
  - pip install git+https://github.com/elastic/elasticsearch-py.git#egg=elasticsearch
  
script:
  - 'case "${ES_VERSION}" in
    5.4.1|5.3.3)
      pip install  "elasticsearch-dsl>=5.0.0,<6.0.0" || travis_terminate 1
      ;;
    2.4.5)
      pip install  "elasticsearch>=2.0.0,<3.0.0" || travis_terminate 1
      ;;
    1.7.6)
      pip install  "elasticsearch>=1.0.0,<2.0.0"|| travis_terminate 1
      ;;
    *)
      travis_terminate 1
      ;;
    esac'
  - pip install -r requirements.txt
  - pip install coveralls nose2 nose2-cov
  - coverage run --source=nxtool -m nose2.__main__ -v

after_success:
  - coveralls
